// Generated by AI. Original prompt: Write comprehensive system tests for Turn_Manager.cs
using NUnit.Framework;
using UnityEngine;
using UnityEngine.TestTools;
using System.Collections;
using PropertyTycoon;
using System.Reflection;

public class TurnManagerSystemTests
{
    private GameObject turnManagerObject;
    private GameObject propertyManagerObject;

    private Turn_Script turnManager;

    private PropertyManager pmanager;
    [UnitySetUp]
    public IEnumerator SetUp()
    {
        turnManagerObject = new GameObject();
        turnManager = turnManagerObject.AddComponent<Turn_Script>();
        
        propertyManagerObject = new GameObject();
        pmanager = propertyManagerObject.AddComponent<PropertyManager>();

        // Initialize players and dependencies
        turnManager.players = new boardPlayer[2];
        for (int i = 0; i < 2; i++)
        {
            GameObject playerObj = new GameObject();
            turnManager.players[i] = playerObj.AddComponent<boardPlayer>();
            turnManager.players[i].name="player "+i.ToString();
        }
        turnManager.pmanager=pmanager; //Assign propertymanager to turnmanager
        turnManager.Start();
        yield return null; // Allow Awake() to initialize
    }

    [TearDown]
    public void TearDown()
    {
        Object.DestroyImmediate(turnManagerObject);
        foreach (var player in turnManager.players) Object.DestroyImmediate(player.gameObject);
        Time.timeScale=1f;
    }

    // System Test: Verify full turn cycle advances rounds
   [UnityTest]
    public IEnumerator Test_RoundIncrementsAfterFullCycle()
    {
        // Save original time scale and speed up time
        // this worked apparently???????
        float originalTimeScale = Time.timeScale;
        Time.timeScale = 100f; // Makes 0.5s delay ~0.005s
        
        turnManager.currentPlayerIndex = 1; // Last player in a 2-player game
        turnManager.turnEnded = true; // Enable ending the turn
        for (int i=0;i<2;i++){
        turnManager.EndTurnButtonClicked();
        yield return new WaitUntil(() => turnManager.currentPlayerIndex == 0); // Wait for index 
        }
        Time.timeScale = originalTimeScale; //fix timescale after
        Assert.AreEqual(2, turnManager.round); // Round should increment after all players
    }
    
    // System Test: Verify player movement updates TileCount
    [UnityTest]
    public IEnumerator Test_PlayerMovePhase_UpdatesTilePosition()
    {
        turnManager.pmanager=pmanager;
        boardPlayer currentPlayer = turnManager.players[0];
        int initialTile = currentPlayer.TileCount;
        // Simulate dice roll
        turnManager.isWaitingForRoll = false;
        yield return turnManager.StartCoroutine(turnManager.PlayerMovePhase(currentPlayer,true));
        Assert.Greater(currentPlayer.TileCount, initialTile);
    }
    // TurnManagerSystemTests.cs
    [UnityTest]
    public IEnumerator Test_JailMechanics()
    {
        // Setup
        var jailedPlayer = turnManager.players[0];
        jailedPlayer.inJail = true;
        jailedPlayer.TileCount = 11;

         // Test 3 turns in jail
        for(int i=0;i<3;i++)
        {
            yield return turnManager.StartCoroutine(turnManager.PlayerMovePhase(jailedPlayer, true));
            Assert.AreEqual(11, jailedPlayer.TileCount);
            i+=1;
        } 



        // Verify release after 3 turns
        yield return turnManager.StartCoroutine(turnManager.PlayerMovePhase(jailedPlayer, true));
        Assert.IsFalse(jailedPlayer.inJail);
        Assert.AreNotEqual(11, jailedPlayer.TileCount);
    }

    /*
    This isnt meant to be here yet, need to implement double dice
    [UnityTest]
    public IEnumerator Test_DoubleDiceMovement()
    {
        // Setup
        turnManager.testMode = false;
        var currentPlayer = turnManager.players[0];
        int initialTile = currentPlayer.TileCount;
        // Execute roll
        turnManager.StartCoroutine(turnManager.PlayerMovePhase(currentPlayer));
        yield return new WaitForSeconds(0.1f);
        
        // Verify valid movement range
        int movedTiles = currentPlayer.TileCount - initialTile;
        Assert.IsTrue(movedTiles >= 2 && movedTiles <= 12);


    }
    */

    //Test to make sure jailed players dont need rent
    [UnityTest]
    public IEnumerator Test_RentSkipWhenOwnerJailed()
    {
        //A LOT of setup needed here- rent transcations needed all players made
        boardPlayer player = turnManager.players[0];
        boardPlayer ownerPlayer2 = turnManager.players[1];
        Player ownerPlayer = new Player("testplayer",ownerPlayer2);

        player.inJail=true;
        player.balance=1000;
        var property = new Property ("Test property",0,"Brown", 10);
        ownerPlayer2.BuyTile(property,ownerPlayer);
        player.TileCount=9;
        //Move player onto owned tile
        yield return turnManager.StartCoroutine(turnManager.PlayerMovePhase(player,true,1,0));
        Assert.AreEqual(1000, player.balance);
    }
}




