// Generated by AI. Original prompt: Write system tests for Player.cs
using NUnit.Framework;
using UnityEngine.TestTools;
using System.Collections;
using PropertyTycoon;

public class PlayerSystemTests
{
    // System Test: Rent payment between players
    [UnityTest]
    public IEnumerator Test_RentTransaction()
    {
        Player payer = new Player("Payer", new boardPlayer());
        Player receiver = new Player("Receiver", new boardPlayer());
        
        payer.Debit(100);
        receiver.Credit(100);
        
        Assert.AreEqual(1400, payer.Balance);
        Assert.AreEqual(1600, receiver.Balance);
        yield return null;
    }
}