// Generated by AI. Original prompt: Write system tests for Property.cs
using NUnit.Framework;
using UnityEngine.TestTools;
using PropertyTycoon;

public class PropertySystemTests
{
    // System Test: Full ownership lifecycle
    [Test]
    public void Test_PropertyOwnershipLifecycle()
    {
        Property prop = new Property("Test", 100, "Blue", 20);
        Player player = new Player("Owner", null);
        
        // Buy property
        prop.switchOwner(player);
        Assert.IsTrue(prop.owned);
        Assert.AreEqual(player, prop.owner);
        
        // Sell property
        prop.removeOwner();
        Assert.IsFalse(prop.owned);
        Assert.IsNull(prop.owner);
    }
}